system:
  admin:
    identity: scott
    secret: tiger
    max-task-count: 3
datasources:
  default:
    url: 'jdbc:h2:mem:micronaut-sample;LOCK_TIMEOUT=10000;MODE=PostgreSQL'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
    dialect: H2
