micronaut:
  application:
    name: micronaut-sample
  router:
    static-resources:
      default:
        enabled: true
        mapping: /public/**
        paths: classpath:public
  security:
    authentication: session
    redirect:
      login-success: /tasks
      login-failure: /login
      logout: /login
      unauthorized:
        enabled: true
        url: /login
      forbidden:
        enabled: true
        url: /login
    intercept-url-map:
      -
        pattern: /login
        access:
          - isAnonymous()
      -
        pattern: /tasks/**
        access:
          - SYSTEM_ADMIN
      -
        pattern: /public/**
        access:
          - isAnonymous()
      -
        pattern: /**
        access:
          - isAuthenticated()
    endpoints:
      login:
        enabled: true
        path: /login
      logout:
        enabled: true
        path: /logout
        get-allowed: true
flyway:
  datasources:
    default:
      locations: db/migration
system:
  admin:
    identity: set-to-admin-identity
    secret: set-to-admin-secret
    max-task-count: 1000
