version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - setup_remote_docker:

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "settings.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-

      - run:
          name: Update dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "settings.gradle" }}

      - run:
          name: Run verGJF
          command: ./gradlew verGJF

      - run:
          name: Run test
          command: ./gradlew test

      - store_artifacts:
          path: build/reports
          prefix: jacoco

      - store_test_results:
          path: build/test-results
          prefix: test-results

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
